---
- hosts: web
  become: True
  tasks:
    - name: Install python pip
      apt:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: webserver
        image: "arunastu/mywebapp:${DOCKER_TAG}"
        state: started
        ports:
          - "80:80"
...
