---
- hosts: web
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: webserver
        image: "arunastu/mywebapp:${DOCKER_TAG}"
        state: started
        Peblished_ports:
          - 0.0.0.0:80:80
...
